method:
  2_ordem: 4
  fluencia: 2
coef:
  gamma_f: 1
  gamma_c: 1.4
  gamma_s: 1.15
  gamma_3: 1.1
  
materials: 
  concrete:
    fck: 40
  steel:
    fyk: 500
    mod_es: 210

elemento:
  L: 1000 #cm
  vinculacao: 1 #tipo_vinculacao: 0=secao-unica, 1=Bi-rotulado, 2=Engaste-livre
  secao:
    tipo_secao: "circular" 
  dim_x: 120
  dim_y: 120
  hole: 0